backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "content/pages"     # Ordner für Seiten (muss existieren)
    create: true
    extension: "md"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Inhalt"
        name: "body"
        widget: "markdown"
