backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # Ordner für hochgeladene Bilder
public_folder: "/images/uploads"    # Öffentlicher Pfad zu den Bildern

collections:
  - name: "pages"                   # Interner Name der Sammlung
    label: "Seiten"                 # Anzeige im Dashboard
    folder: ""                      # Root-Verzeichnis verwenden
    create: true                    # Erlaubt das Erstellen neuer Seiten
    extension: "html"               # Dateiendung der Seiten (HTML)
    format: "html"                  # Format explizit als HTML angeben
    fields:                         # Felder, die im Editor angezeigt werden
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Inhalt"
        name: "body"
        widget: "text"              # Text-Widget verwenden für HTML-Inhalt
