backend:
  name: git-gateway
  branch: main # oder der Branch, den du für dein Projekt nutzt

media_folder: "images/uploads" # Ordner für hochgeladene Bilder
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: ""
    create: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
